"""empty message

Revision ID: 845fa794e9f8
Revises: bfbc308f3f76
Create Date: 2024-05-16 13:28:05.951065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '845fa794e9f8'
down_revision = 'bfbc308f3f76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
